### ISSUE TITLE
Github API access error

### ISSUE THREAD

**Issue by lisad** [dtinit/portmap#114]
Seen in cloud logs after articles failed to load

 Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/portmap/core/admin.py", line 55, in populate
    get_content_files()
  File "/srv/portmap/core/articles.py", line 40, in get_content_files
    raise RuntimeError("Failed to access Github API.")
RuntimeError: Failed to access Github API.

**Comment by lisad** [comment]
This isn't what's really happening - it's 
"ERROR:root:Error accessing Github API: Failed to process article 'watch-history1.md'. Check for headers and datatype values."

The nesting of the try blocks in get_content_files is causing one error to get swallowed by the other
